"use client"

import { useState } from "react"
import "./globals.css"
import Header from "../Layout/components/Header"
import Footer from "../Layout/components/Footer"
import MobileMenu from "./components/MobileMenu"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  const [isMobileMenuShown, setIsMobileMenuShown] = useState(false)

  return (
    <html lang="en">
      <body className="body min-h-screen flex flex-col">
        <Header onClickMobileMenu={() => setIsMobileMenuShown(!isMobileMenuShown)}/>
        {isMobileMenuShown && <MobileMenu />}
        {children}
        <div className="mt-auto">
          <Footer />
        </div>
      </body>
    </html>
  )
}

export default RootLayout
